---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# Action test/validation workflow
name: "Test GitHub Action 🧪"

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions: {}

jobs:
  ### Test the GitHub Action in this Repository ###
  tests:
    name: "Test local GitHub Action"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 5
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: "Running local action: ${{ github.repository }} [path]"
        uses: ./
        with:
          path: /tmp/prescan-go-coverage-ubuntu.sh
          # yamllint disable-line rule:line-length
          url: "https://raw.githubusercontent.com/o-ran-sc/ci-management/refs/heads/master/jjb/com-golog/prescan-golog-go-ubuntu.sh"

      - name: "Running local action: ${{ github.repository }}"
        uses: ./
        with:
          # yamllint disable-line rule:line-length
          url: "https://raw.githubusercontent.com/o-ran-sc/ci-management/refs/heads/master/jjb/com-golog/prescan-golog-go-ubuntu.sh"

      - name: "Running local action: ${{ github.repository }} [no_clobber]"
        uses: ./
        with:
          no_clobber: true
          wget_flags: ''
          # yamllint disable-line rule:line-length
          url: "https://raw.githubusercontent.com/o-ran-sc/ci-management/refs/heads/master/jjb/com-golog/prescan-golog-go-ubuntu.sh"
